name: ClusterEnv

dependencies:
  - python=3.9.2
  - anaconda
  - pip
  - pip:
    - astunparse==1.6.3
    - Brian2==2.5.4
    - cachetools==5.3.2
    - certifi==2023.7.22
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.2.0
    - cuda-python==12.3.0
    - cupy==12.3.0
    - cycler==0.12.1
    - Cython==3.0.8
    - debugpy==1.8.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - elasticdeform==0.5.0
    - fastrlock==0.8.2
    - flatbuffers==23.5.26
    - fonttools==4.44.3
    - gast==0.5.4
    - gitdb==4.0.11
    - GitPython==3.1.40
    - google-auth==2.23.4
    - google-auth-oauthlib==1.1.0
    - google-pasta==0.2.0
    - grpcio==1.59.3
    - h5py==3.10.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - Jinja2==3.1.3
    - keras==2.15.0
    - kiwisolver==1.4.5
    - libclang==16.0.6
    - Markdown==3.5.1
    - MarkupSafe==2.1.3
    - matplotlib==3.8.2
    - ml-dtypes==0.2.0
    - mpmath==1.3.0
    - numpy==1.26.2
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.2
    - Pillow==10.1.0
    - pipreqs==0.4.13
    - protobuf==4.23.4
    - psutil==5.9.6
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - PyYAML==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.11.3
    - sentry-sdk==1.37.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.12
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-intel==2.15.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.3.0
    - typing-extensions==4.8.0
    - urllib3==2.1.0
    - wandb==0.16.0
    - Werkzeug==3.0.1
    - wrapt==1.14.1
    - yarg==0.1.9
    - zipp==3.17.0
